apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo
  annotations:
    jenkins.url: "http://jenkins.joindevops.com.build/"
    imageregistry: "https://hub.docker.com/repositories"
spec:
  containers:
  - name: nginx
    image: nginx


